query getObjects(
  $bucket_slug: String!
  $read_key: String!
) {
  getObjects(
    bucket_slug: $bucket_slug
    read_key: $read_key
  ) {
    objects {
      title
      id
      metadata
      slug
    }
  }
}
