query getObject(
  $folder: String!
  $bucket_slug: String!
  $read_key: String!
  $object_id: ID!
) {
  getObject(
    bucket_slug: $bucket_slug
    read_key: $read_key
    object_id: $object_id
  ) {
    title
    content
    metadata
  }

  getMedia(
    input: {
      folder: $folder
    }
    bucket_slug: $bucket_slug
    read_key: $read_key
  ) {
      media {
        imgix_url
        metadata
      }
    }
  }
