query getObject(
  $folder: String!
  $bucket_slug: String!
  $read_key: String!
  $object_id: ID!
) {
  getObject(
    bucket_slug: $bucket_slug
    read_key: $read_key
    object_id: $object_id
  ) {
    content
  }

  getMedia(
    bucket_slug: $bucket_slug
    read_key: $read_key
    input: {
      query: {
        folder: $folder
      }
    }
    ) {
    media {
      imgix_url
      metadata
    }
  }
}
